name: Bug Report (Web Interface)
description: Mastodon の Web インターフェイスを使用していて、何かが期待どおりに動作しない場合
labels: [bug, 'status/to triage', 'area/web interface']
assignees: 'mimikun'
body:
  - type: markdown
    attributes:
      value: |
        以前に報告されたものでも、すでに修正されたものでもない、新しいバグを提出していることを確認してください。

        issueのタイトルは簡潔かつ明確にしてください。
  - type: textarea
    attributes:
      label: 問題の再現手順
      description: どのように操作しましたか？
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: input
    attributes:
      label: 期待される振る舞い
      description: どのような振る舞いが期待されていましたか？
    validations:
      required: true
  - type: input
    attributes:
      label: 実際の振る舞い
      description: 実際にはどのように振る舞われましたか？
    validations:
      required: true
  - type: textarea
    attributes:
      label: 詳細な説明
    validations:
      required: false
  - type: input
    attributes:
      label: Mastodon instance
      description: issue が発生した Mastodon インスタンスのアドレス
      placeholder: mstdn.mimikun.jp
    validations:
      required: true
  - type: input
    attributes:
      label: Mastodon version
      description: |
        これは About ページの下部に表示されます。 例: `v4.1.2+nightly-20230627`
      placeholder: v4.1.2
    validations:
      required: true
  - type: input
    attributes:
      label: ブラウザ名とバージョン
      description: |
        このバグが発生したときに使用していたブラウザは何ですか？バージョンも明記してください。
      placeholder: Firefox 105.0.3
    validations:
      required: true
  - type: input
    attributes:
      label: OS
      description: |
        お使いのOSは？バージョンも明記してください。
      placeholder: macOS 13.4.1
    validations:
      required: true
  - type: textarea
    attributes:
      label: 技術的な詳細
      description: |
        その他、技術的な詳細があれば教えてください。これには、完全なエラーログ、インスペクタの出力などを含むことができます。
    validations:
      required: false
