name: Bug Report (server / API)
description: |
  Webインターフェースを使用していないにもかかわらず、何かが期待通りに動作しない場合
labels: [bug, 'status/to triage']
assignees: 'mimikun'
body:
  - type: markdown
    attributes:
      value: |
        以前に報告されたものでも、すでに修正されたものでもない、新しいバグを提出していることを確認してください。

        issueのタイトルは簡潔かつ明確にしてください。
  - type: textarea
    attributes:
      label: 問題の再現手順
      description: どのように操作しましたか？
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: input
    attributes:
      label: 期待される振る舞い
      description: どのような振る舞いが期待されていましたか？
    validations:
      required: true
  - type: input
    attributes:
      label: 実際の振る舞い
      description: 実際にはどのように振る舞われましたか？
    validations:
      required: true
  - type: textarea
    attributes:
      label: 詳細な説明
    validations:
      required: false
  - type: input
    attributes:
      label: Mastodon instance
      description: issue が発生した Mastodon インスタンスのアドレス
      placeholder: mstdn.mimikun.jp
    validations:
      required: false
  - type: input
    attributes:
      label: Mastodon version
      description: |
        これは About ページの下部に表示されます。 例: `v4.1.2+nightly-20230627`
      placeholder: v4.1.2
    validations:
      required: false
  - type: textarea
    attributes:
      label: 技術的な詳細
      description: |
        ログやエラーのトレースなど、技術的な詳細があれば教えてください。
      value: |
        ご自身のMastodonサーバーでこの現象が発生している場合は、以下にご記入ください:
        - Ruby version: (from `ruby --version`, eg. v3.1.2)
        - Node.js version: (from `node --version`, eg. v18.16.0)
    validations:
      required: false
