name: 機能リクエスト
description: 提案があります
labels: [suggestion]
assignees: 'mimikun'
body:
  - type: markdown
    attributes:
      value: |
        Please use a concise and distinct title for the issue.

        Consider: Could it be implemented as a 3rd party app using the REST API instead?
  - type: textarea
    attributes:
      label: ピッチ
      description: 機能のアイデアを説明してください。以前に提案/実装/却下されていないことを確認してください。
    validations:
      required: true
  - type: textarea
    attributes:
      label: モチベーション
      description: なぜこの機能が必要だと思いますか?だれにとって有益ですか？
    validations:
      required: true
